# Generated by Django 6.0.7 on 2026-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('editor_in_chief', 'Baş redaktor'), ('editor', 'Redaktor'), ('journalist', 'Jurnalist'), ('content_manager', 'Kontent meneceri')], default='journalist', max_length=20),
        ),
    ]
