# Generated by Django 6.0.7 on 2026-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Qaralama'), ('pending_review', 'Nəzərdən keçirilir'), ('scheduled', 'Planlaşdırılıb'), ('published', 'Dərc olunub'), ('archived', 'Arxivləşdirilib')], db_index=True, default='draft', max_length=20),
        ),
    ]
