# Generated by Django 6.0.7 on 2026-07-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsvideocover'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='show_author_name',
            field=models.BooleanField(default=False),
        ),
    ]
