from django import forms
from django.utils import timezone

from apps.categories.models import Category
from apps.tags.models import Tag

from .models import News

FIELD_CLASS = 'form-input'


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = [
            'title', 'slug', 'short_description', 'content',
            'category', 'tags', 'status', 'published_at',
            'is_featured', 'is_breaking', 'featured_image',
            'meta_title', 'meta_description', 'meta_keywords', 'canonical_url',
            'og_title', 'og_description', 'og_image', 'robots_index', 'robots_follow',
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': FIELD_CLASS + ' editor__title-input', 'placeholder': 'Xəbər başlığını daxil edin...', 'data-role': 'title-input'}),
            'slug': forms.TextInput(attrs={'class': FIELD_CLASS, 'data-role': 'slug-input'}),
            'short_description': forms.Textarea(attrs={'class': FIELD_CLASS + ' editor__excerpt-input', 'rows': 2, 'placeholder': 'Qısa təsvir (dek)...'}),
            'category': forms.Select(attrs={'class': FIELD_CLASS}),
            'tags': forms.SelectMultiple(attrs={'class': FIELD_CLASS, 'data-role': 'tag-input'}),
            'status': forms.Select(attrs={'class': FIELD_CLASS}),
            'published_at': forms.DateTimeInput(attrs={'class': FIELD_CLASS, 'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            # Not visible widgets — static/js/cms/image-pickers.js sets these
            # hidden inputs' values once an image is staged/cropped via the
            # Media Library pipeline (see templates/cms/news_form.html).
            'featured_image': forms.HiddenInput(attrs={'data-role': 'picker-input'}),
            'og_image': forms.HiddenInput(attrs={'data-role': 'picker-input'}),
            'meta_title': forms.TextInput(attrs={'class': FIELD_CLASS, 'placeholder': 'Axtarış nəticələrində görünəcək başlıq'}),
            'meta_description': forms.Textarea(attrs={'class': FIELD_CLASS, 'rows': 3, 'placeholder': 'Qısa SEO təsviri (160 simvola qədər)'}),
            'meta_keywords': forms.TextInput(attrs={'class': FIELD_CLASS, 'placeholder': 'açar, sözlər, vergüllə'}),
            'canonical_url': forms.URLInput(attrs={'class': FIELD_CLASS, 'placeholder': 'https://...'}),
            'og_title': forms.TextInput(attrs={'class': FIELD_CLASS, 'placeholder': 'Sosial şəbəkələrdə görünəcək başlıq'}),
            'og_description': forms.Textarea(attrs={'class': FIELD_CLASS, 'rows': 3}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].choices = self._category_choices()
        self.fields['tags'].queryset = Tag.objects.all()
        self.fields['published_at'].input_formats = ['%Y-%m-%dT%H:%M']
        self.fields['featured_image'].required = False
        self.fields['og_image'].required = False
        # Auto-generated by News.save() (apps.core.utils.az_slugify) when left
        # blank — TZ "Slugs": "Automatically generated... Editable by
        # administrators." Required=False lets the auto-generation apply.
        self.fields['slug'].required = False

    @staticmethod
    def _category_choices():
        """Flat list with subcategories indented under their parent.

        Overrides only the *display* choices — `ModelChoiceField.clean()`
        still validates against `self.fields['category'].queryset`
        (unchanged, set by ModelForm from `News.category`'s relation), so
        this can't be used to submit a category the field wouldn't
        otherwise accept.
        """
        choices = [('', '---------')]
        for parent in Category.objects.active().visible().top_level().order_by('order'):
            choices.append((parent.pk, parent.name))
            for child in parent.children.filter(is_active=True, is_deleted=False).order_by('order'):
                choices.append((child.pk, f'— {child.name}'))
        return choices

    def clean(self):
        cleaned_data = super().clean()
        status = cleaned_data.get('status')
        published_at = cleaned_data.get('published_at')

        if status == News.Status.SCHEDULED:
            if not published_at:
                self.add_error('published_at', 'Planlaşdırılmış xəbər üçün nəşr tarixi mütləqdir.')
            elif published_at <= timezone.now():
                self.add_error('published_at', 'Planlaşdırılmış tarix gələcəkdə olmalıdır.')
        elif status == News.Status.PUBLISHED and not published_at:
            cleaned_data['published_at'] = timezone.now()

        return cleaned_data
