# Generated by Django 6.0.7 on 2026-07-11 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_migrate_social_link_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_facebook',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_instagram',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_twitter',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_youtube',
        ),
    ]
