# Generated by Django 6.0.7 on 2026-07-27 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_remove_social_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_category_sections_count',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
