# Generated by Django 6.0.7 on 2026-07-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_sitesettings_home_category_sections_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_show_all_categories',
            field=models.BooleanField(default=False),
        ),
    ]
