# Generated by Django 6.0.7 on 2026-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Uğurlu giriş'), ('login_failed', 'Uğursuz giriş cəhdi'), ('logout', 'Çıxış'), ('article_created', 'Xəbər yaratdı'), ('article_updated', 'Xəbəri redaktə etdi'), ('article_deleted', 'Xəbəri sildi'), ('article_restored', 'Xəbəri bərpa etdi')], max_length=30),
        ),
    ]
