# Generated by Django 6.0.7 on 2026-07-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Uğurlu giriş'), ('login_failed', 'Uğursuz giriş cəhdi'), ('logout', 'Çıxış'), ('article_created', 'Xəbər yaratdı'), ('article_updated', 'Xəbəri redaktə etdi'), ('article_deleted', 'Xəbəri sildi'), ('article_restored', 'Xəbəri bərpa etdi'), ('media_uploaded', 'Fayl yüklədi'), ('media_replaced', 'Faylı əvəz etdi'), ('media_deleted', 'Faylı sildi'), ('category_created', 'Kateqoriya yaratdı'), ('category_updated', 'Kateqoriyanı redaktə etdi'), ('category_deleted', 'Kateqoriyanı sildi'), ('category_restored', 'Kateqoriyanı bərpa etdi'), ('tag_created', 'Etiket yaratdı'), ('tag_updated', 'Etiketi redaktə etdi'), ('tag_deleted', 'Etiketi sildi'), ('tag_merged', 'Etiketləri birləşdirdi'), ('folder_created', 'Qovluq yaratdı'), ('folder_renamed', 'Qovluğun adını dəyişdi'), ('folder_deleted', 'Qovluğu sildi'), ('user_created', 'İstifadəçi yaratdı'), ('user_updated', 'İstifadəçini redaktə etdi'), ('user_role_changed', 'İstifadəçinin rolunu dəyişdi'), ('user_activated', 'İstifadəçini aktivləşdirdi'), ('user_deactivated', 'İstifadəçini deaktiv etdi'), ('user_password_reset', 'Şifrə sıfırlama göndərdi')], max_length=30),
        ),
    ]
