# Generated by Django 6.0.7 on 2026-07-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Uğurlu giriş'), ('login_failed', 'Uğursuz giriş cəhdi'), ('login_blocked', 'Bloklanmış giriş cəhdi (həddindən artıq cəhd)'), ('logout', 'Çıxış'), ('article_created', 'Xəbər yaratdı'), ('article_updated', 'Xəbəri redaktə etdi'), ('article_deleted', 'Xəbəri sildi'), ('article_restored', 'Xəbəri bərpa etdi'), ('article_purged', 'Xəbəri həmişəlik sildi'), ('media_uploaded', 'Fayl yüklədi'), ('media_replaced', 'Faylı əvəz etdi'), ('media_deleted', 'Faylı sildi'), ('media_moved', 'Faylı başqa qovluğa köçürdü'), ('category_created', 'Kateqoriya yaratdı'), ('category_updated', 'Kateqoriyanı redaktə etdi'), ('category_deleted', 'Kateqoriyanı sildi'), ('category_restored', 'Kateqoriyanı bərpa etdi'), ('category_purged', 'Kateqoriyanı həmişəlik sildi'), ('tag_created', 'Etiket yaratdı'), ('tag_updated', 'Etiketi redaktə etdi'), ('tag_deleted', 'Etiketi sildi'), ('tag_merged', 'Etiketləri birləşdirdi'), ('folder_created', 'Qovluq yaratdı'), ('folder_renamed', 'Qovluğun adını dəyişdi'), ('folder_deleted', 'Qovluğu sildi'), ('user_created', 'İstifadəçi yaratdı'), ('user_updated', 'İstifadəçini redaktə etdi'), ('user_role_changed', 'İstifadəçinin rolunu dəyişdi'), ('user_activated', 'İstifadəçini aktivləşdirdi'), ('user_deactivated', 'İstifadəçini deaktiv etdi'), ('user_password_reset', 'Şifrə sıfırlama göndərdi'), ('settings_updated', 'Tənzimləmələri yenilədi'), ('page_created', 'Səhifə yaratdı'), ('page_updated', 'Səhifəni redaktə etdi'), ('page_deleted', 'Səhifəni sildi'), ('ad_created', 'Reklam kampaniyası yaratdı'), ('ad_updated', 'Reklam kampaniyasını redaktə etdi'), ('ad_deleted', 'Reklam kampaniyasını sildi'), ('ad_restored', 'Reklam kampaniyasını bərpa etdi'), ('ad_purged', 'Reklam kampaniyasını həmişəlik sildi'), ('social_link_created', 'Sosial şəbəkə linki yaratdı'), ('social_link_updated', 'Sosial şəbəkə linkini redaktə etdi'), ('social_link_deleted', 'Sosial şəbəkə linkini sildi')], max_length=30),
        ),
    ]
