# Generated by Django 6.0.7 on 2026-07-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
